# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine: true
    php:
      version: 7.2.8
    node:
      version: 5.7.0
    steps:
    - checkout
